#!/bin/bash
# WSL DNS Fix Script
#
# Resolves common DNS issues in WSL2 by regenerating /etc/resolv.conf and
# optionally configuring WSL to prevent automatic DNS generation.
#
# Features:
# - Backs up current resolv.conf
# - Regenerates DNS configuration with reliable nameservers
# - Optionally disables automatic DNS generation in wsl.conf
# - Provides options for Google DNS, Cloudflare DNS, or custom servers
# - Useful for fixing "Temporary failure in name resolution" errors
#
# Common WSL2 DNS issues occur when:
# - VPN connections interfere with DNS resolution
# - Windows DNS settings conflict with WSL
# - /etc/resolv.conf gets corrupted or misconfigured
# - WSL automatically generates incorrect DNS entries
#
# Usage:
# $ ./fix_dns.sh [--disable-auto-dns]
# $ chmod +x ~/fix_dns.sh

# --- Configuration ---
BACKUP_FILE="/etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)"
DISABLE_AUTO_DNS=false

if [ "$1" == "--disable-auto-dns" ]; then
    DISABLE_AUTO_DNS=true
fi

echo "--- 🌍 WSL2 DNS Fix Script ---"
echo ""

# --- Backup current resolv.conf ---
if [ -f /etc/resolv.conf ]; then
    echo "📋 Backing up current /etc/resolv.conf to $BACKUP_FILE"
    sudo cp /etc/resolv.conf "$BACKUP_FILE"
    echo "✅ Backup created"
    echo ""
fi

# --- Show current DNS servers ---
echo "Current DNS servers:"
if [ -f /etc/resolv.conf ]; then
    grep "^nameserver" /etc/resolv.conf || echo "  (none configured)"
else
    echo "  /etc/resolv.conf does not exist"
fi
echo ""

# --- Prompt for DNS choice ---
echo "Select DNS servers to use:"
echo "1) Google DNS (8.8.8.8, 8.8.4.4) - Fast and reliable"
echo "2) Cloudflare DNS (1.1.1.1, 1.0.0.1) - Privacy-focused"
echo "3) Google + Cloudflare (8.8.8.8, 1.1.1.1) - Best of both"
echo "4) Keep Windows DNS (try to use host settings)"
echo "5) Custom DNS servers"
echo ""
read -p "Enter choice (1-5) [default: 1]: " DNS_CHOICE
DNS_CHOICE=${DNS_CHOICE:-1}

case $DNS_CHOICE in
    1)
        DNS_SERVERS="8.8.8.8\n8.8.4.4"
        DNS_DESC="Google DNS"
        ;;
    2)
        DNS_SERVERS="1.1.1.1\n1.0.0.1"
        DNS_DESC="Cloudflare DNS"
        ;;
    3)
        DNS_SERVERS="8.8.8.8\n1.1.1.1"
        DNS_DESC="Google + Cloudflare DNS"
        ;;
    4)
        # Try to extract Windows DNS
        HOST_IP=$(ip route show default | awk '{print $3}')
        DNS_SERVERS="$HOST_IP\n8.8.8.8"
        DNS_DESC="Windows Host + Google DNS"
        ;;
    5)
        read -p "Enter DNS servers (comma-separated): " CUSTOM_DNS
        DNS_SERVERS=$(echo "$CUSTOM_DNS" | tr ',' '\n')
        DNS_DESC="Custom DNS"
        ;;
    *)
        echo "❌ Invalid choice. Exiting."
        exit 1
        ;;
esac

echo ""
echo "--- 🔧 Applying DNS Configuration ---"
echo "Using: $DNS_DESC"
echo ""

# Remove immutable flag if set
sudo chattr -i /etc/resolv.conf 2>/dev/null

# Create new resolv.conf
echo "# DNS configuration generated by fix_dns.sh" | sudo tee /etc/resolv.conf > /dev/null
echo "# Generated on $(date)" | sudo tee -a /etc/resolv.conf > /dev/null
echo "" | sudo tee -a /etc/resolv.conf > /dev/null
echo -e "$DNS_SERVERS" | while read -r server; do
    if [ -n "$server" ]; then
        echo "nameserver $server" | sudo tee -a /etc/resolv.conf > /dev/null
    fi
done

echo "✅ /etc/resolv.conf updated"
echo ""

# --- Optionally disable automatic DNS generation ---
if [ "$DISABLE_AUTO_DNS" == true ]; then
    echo "--- ⚙️  Disabling Automatic DNS Generation ---"
    
    WSL_CONF="/etc/wsl.conf"
    
    # Check if wsl.conf exists and has [network] section
    if [ -f "$WSL_CONF" ]; then
        sudo cp "$WSL_CONF" "${WSL_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    fi
    
    # Add or update network section
    if grep -q "^\[network\]" "$WSL_CONF" 2>/dev/null; then
        # Section exists, check for generateResolvConf
        if grep -q "^generateResolvConf" "$WSL_CONF"; then
            sudo sed -i 's/^generateResolvConf.*/generateResolvConf = false/' "$WSL_CONF"
        else
            sudo sed -i '/^\[network\]/a generateResolvConf = false' "$WSL_CONF"
        fi
    else
        # Add entire section
        echo "" | sudo tee -a "$WSL_CONF" > /dev/null
        echo "[network]" | sudo tee -a "$WSL_CONF" > /dev/null
        echo "generateResolvConf = false" | sudo tee -a "$WSL_CONF" > /dev/null
    fi
    
    # Make resolv.conf immutable to prevent changes
    sudo chattr +i /etc/resolv.conf
    
    echo "✅ Automatic DNS generation disabled in $WSL_CONF"
    echo "✅ /etc/resolv.conf set to immutable"
    echo ""
    echo "⚠️  You need to restart WSL for this change to take full effect:"
    echo "   Run in PowerShell: wsl --shutdown"
    echo "   Then restart your WSL terminal"
fi

echo ""
echo "--- 🧪 Testing DNS Resolution ---"

# Test DNS resolution
if nslookup google.com &> /dev/null; then
    echo "✅ DNS resolution working (google.com resolved)"
else
    echo "❌ DNS resolution failed (could not resolve google.com)"
    echo "   You may need to restart WSL: wsl --shutdown (from PowerShell)"
fi

echo ""
echo "New DNS servers:"
grep "^nameserver" /etc/resolv.conf

echo ""
echo "💡 If issues persist, try:"
echo "   1. Restart WSL: wsl --shutdown (from Windows PowerShell)"
echo "   2. Check Windows firewall settings"
echo "   3. Temporarily disable VPN if connected"
